src/General/Controllers/PresentationController.cs
using General.Model;
using Microsoft.AspNet.Mvc;
using MongoDB.Bson;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MyNamespace
{
    public class PresentationController : Controller
    {
        readonly IPresentationRepository _presentationRepository;

        public PresentationController(IPresentationRepository presentationRepository)
        {
            _presentationRepository = presentationRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<Presentations>> GetAll()
        {
            var presentations = await _presentationRepository.AllPresentations();
            return presentations;
        }

        [HttpPost]
        public void Create([FromBody] Presentations presentations)
        {
            if (!ModelState.IsValid)
            {
                Context.Response.StatusCode = 400;
            }
            else
            {
                _presentationRepository.Add(presentations);

                string url = Url.RouteUrl("GetByIdRoute", new { id = presentations.Id.ToString() }, Request.Scheme, Request.Host.ToUriComponent());
                Context.Response.StatusCode = 201;
                Context.Response.Headers["Location"] = url;
            }
        }

        public IActionResult Edit(string id)
        {
            var model = _presentationRepository.Get(new ObjectId(id));
            if (model == null)
            {
                return HttpNotFound();
            }

            return View(model);
        }        

    }
}

src/General/ViewComponents/PresentationListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using General.Model;

namespace General.ViewComponents
{
    public class PresentationListViewComponent : ViewComponent
    {
        readonly IPresentationRepository _presentationRepository;

        public PresentationListViewComponent(IPresentationRepository presentationRepository)
        {
            _presentationRepository = presentationRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var presentations = await _presentationRepository.AllPresentations();
            return View("PresentationList", presentations);
        }
    }
}

src/General/Views/Presentation/Components/PresentationList/PresentationList.cshtml
@model List<General.Model.Presentations>

<h3>Presentations</h3>
<div>
    <div>
        <table>
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Author</th>
                    <th></th>
                </tr>
            </thead>
            @*@foreach (var item in Model)
            {
                <tbody>
                    <tr>
                        <td rowspan="2">@Html.DisplayFor(x => item.PresentationTitle)</td>
                        <td>@Html.DisplayFor(modelItem => item.Author)</td>
                        <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</td>
                    </tr>
                </tbody>
            }*@
        </table>
    </div>
</div>

src/General/Views/Presentation/Edit.cshtml
@model General.Model.Presentations

@using (Html.BeginForm())
{ 
    @Html.HiddenFor(model => model.Id)

    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.PresentationTitle, new { @class = "control-label col-sm-2" })
                @Html.ValidationMessageFor(model => model.PresentationTitle)
                <div class="col-sm-7">
                    @Html.TextBoxFor(model => model.Author, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Author)
                </div>
            </div>
            @foreach (var page in Model.PresentationPages)
            {
                <div class="form-group">
                    <div class="col-sm-7">
                        @Html.TextBoxFor(model => page.Body, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => page.Body)
                    </div>             
                </div>
            }
            <div>
                <input type="submit" value="Save" class="btn btn-lg btn-default" />
            </div>
        </div>
    </div>
}

src/General/Views/Presentation/Index.cshtml
<h2>Presentations</h2>

<div>
    <div class="col-md-4">
        @await Component.InvokeAsync("PresentationList")
    </div>
</div>

src/General/Views/Shared/_Layout.cshtml
@inject IOptions<AppSettings> AppSettings
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewBag.Title - @AppSettings.Options.SiteTitle</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
            <link rel="stylesheet" href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/css/bootstrap-touch-carousel.css"
                  asp-fallback-href="~/lib/bootstrap-touch-carousel/css/bootstrap-touch-carousel.css"
                  asp-fallback-test-class="carousel-caption" asp-fallback-test-property="display" asp-fallback-test-value="none" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">@AppSettings.Options.SiteTitle</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2015 - @AppSettings.Options.SiteTitle</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/jquery.js"></script>
            <script src="~/lib/bootstrap/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/bootstrap-touch-carousel/js/bootstrap-touch-carousel.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-1.10.2.min.js"
                    asp-fallback-src="~/lib/jquery/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.0.0/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap-touch-carousel/0.8.0/js/bootstrap-touch-carousel.js"
                    asp-fallback-src="~/lib/bootstrap-touch-carousel/js/bootstrap-touch-carousel.js"
                    asp-fallback-test="window.Zepto">
            </script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>

src/General/Views/_GlobalImport.cshtml
@using General
@using Microsoft.Framework.OptionsModel
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"